apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: dream-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dream-app
  template:
    metadata:
      labels:
        app: dream-app
    spec:
      containers:
      - name: dream-app
        image: uzzama/dream-test:v2
        ports:
        - containerPort: 80
